/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfas_alumno;

import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Geovanni
 */
public class Reservar_salon extends javax.swing.JFrame {
    String TIPO ,USUARIO,FECHA,HORA,salonr;
    /**
     * Creates new form Administrar_horario
     */
    public Reservar_salon(final String tipo,String nom,String fecha,String hora) {
        initComponents();
            TIPO=tipo;
            USUARIO=nom;
            FECHA=fecha;
            HORA=hora;
            salonr="";
            lb_nomusuario.setText(nom);        
            this.setLocationRelativeTo(null);
            lb_nombresalon.setVisible(false);
            lb_pc.setVisible(false);
            verificar(TIPO);  
            ATUALIZACION_REAL();
            if(TIPO.equals("Docente")){
                rsscalelabel.RSScaleLabel.setScaleLabel(lb_usuario,"src/img/profesor.png");
            }else{
                bt_registrarClase.setVisible(false);
                rsscalelabel.RSScaleLabel.setScaleLabel(lb_usuario,"src/img/estudiante.png");
            } 
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lb_imgPC1 = new javax.swing.JLabel();
        lb_imgPC4 = new javax.swing.JLabel();
        lb_imgPC3 = new javax.swing.JLabel();
        lb_imgPC2 = new javax.swing.JLabel();
        lb_imgPC8 = new javax.swing.JLabel();
        lb_imgPC7 = new javax.swing.JLabel();
        lb_imgPC6 = new javax.swing.JLabel();
        lb_imgPC5 = new javax.swing.JLabel();
        lb_imgPC16 = new javax.swing.JLabel();
        lb_imgPC15 = new javax.swing.JLabel();
        lb_imgPC13 = new javax.swing.JLabel();
        lb_imgPC14 = new javax.swing.JLabel();
        lb_imgPC12 = new javax.swing.JLabel();
        lb_imgPC11 = new javax.swing.JLabel();
        lb_imgPC10 = new javax.swing.JLabel();
        lb_imgPC9 = new javax.swing.JLabel();
        lb_imgPC17 = new javax.swing.JLabel();
        lb_imgPC20 = new javax.swing.JLabel();
        lb_imgPC22 = new javax.swing.JLabel();
        lb_imgPC18 = new javax.swing.JLabel();
        lb_imgPC19 = new javax.swing.JLabel();
        lb_imgPC23 = new javax.swing.JLabel();
        lb_imgPC21 = new javax.swing.JLabel();
        lb_imgPC24 = new javax.swing.JLabel();
        lb_imgPC28 = new javax.swing.JLabel();
        lb_imgPC27 = new javax.swing.JLabel();
        lb_imgPC26 = new javax.swing.JLabel();
        lb_imgPC25 = new javax.swing.JLabel();
        lb_imgPC32 = new javax.swing.JLabel();
        lb_imgPC31 = new javax.swing.JLabel();
        lb_imgPC30 = new javax.swing.JLabel();
        lb_imgPC29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bt_registrarClase = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pn_LAS = new javax.swing.JPanel();
        lb_LAS = new javax.swing.JLabel();
        pn_LDM = new javax.swing.JPanel();
        lb_LDM = new javax.swing.JLabel();
        pn_LDS = new javax.swing.JPanel();
        lb_LDS = new javax.swing.JLabel();
        pn_LPG = new javax.swing.JPanel();
        lb_LPG = new javax.swing.JLabel();
        pn_LSO = new javax.swing.JPanel();
        lb_LSO = new javax.swing.JLabel();
        lb_nombresalon = new javax.swing.JLabel();
        lb_pc = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_usuario = new javax.swing.JLabel();
        lb_nomusuario = new javax.swing.JLabel();
        lb_nomusuario1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_hora = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        libre = new javax.swing.JLabel();
        libre1 = new javax.swing.JLabel();
        libre2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(244, 244, 244));

        lb_imgPC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC1MouseClicked(evt);
            }
        });

        lb_imgPC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC4MouseClicked(evt);
            }
        });

        lb_imgPC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC3MouseClicked(evt);
            }
        });

        lb_imgPC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC2MouseClicked(evt);
            }
        });

        lb_imgPC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC8MouseClicked(evt);
            }
        });

        lb_imgPC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC7MouseClicked(evt);
            }
        });

        lb_imgPC6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC6MouseClicked(evt);
            }
        });

        lb_imgPC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC5MouseClicked(evt);
            }
        });

        lb_imgPC16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC16MouseClicked(evt);
            }
        });

        lb_imgPC15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC15MouseClicked(evt);
            }
        });

        lb_imgPC13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC13MouseClicked(evt);
            }
        });

        lb_imgPC14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC14MouseClicked(evt);
            }
        });

        lb_imgPC12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC12MouseClicked(evt);
            }
        });

        lb_imgPC11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC11MouseClicked(evt);
            }
        });

        lb_imgPC10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC10MouseClicked(evt);
            }
        });

        lb_imgPC9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC9MouseClicked(evt);
            }
        });

        lb_imgPC17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC17MouseClicked(evt);
            }
        });

        lb_imgPC20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC20MouseClicked(evt);
            }
        });

        lb_imgPC22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC22MouseClicked(evt);
            }
        });

        lb_imgPC18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC18MouseClicked(evt);
            }
        });

        lb_imgPC19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC19MouseClicked(evt);
            }
        });

        lb_imgPC23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC23MouseClicked(evt);
            }
        });

        lb_imgPC21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC21MouseClicked(evt);
            }
        });

        lb_imgPC24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC24MouseClicked(evt);
            }
        });

        lb_imgPC28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC28MouseClicked(evt);
            }
        });

        lb_imgPC27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC27MouseClicked(evt);
            }
        });

        lb_imgPC26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC26MouseClicked(evt);
            }
        });

        lb_imgPC25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC25MouseClicked(evt);
            }
        });

        lb_imgPC32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC32MouseClicked(evt);
            }
        });

        lb_imgPC31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC31MouseClicked(evt);
            }
        });

        lb_imgPC30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC30MouseClicked(evt);
            }
        });

        lb_imgPC29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        lb_imgPC29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_imgPC29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgPC29MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel1.setText("Laboratorio de Administración de servidores");

        jPanel4.setBackground(new java.awt.Color(255, 198, 38));

        bt_registrarClase.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bt_registrarClase.setText("Registrar clase");
        bt_registrarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(bt_registrarClase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(bt_registrarClase)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lb_imgPC1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_imgPC2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_imgPC3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_imgPC4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lb_imgPC25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lb_imgPC26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lb_imgPC27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lb_imgPC28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lb_imgPC9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(lb_imgPC17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_imgPC5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_imgPC21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lb_imgPC22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lb_imgPC14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lb_imgPC6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_imgPC8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(lb_imgPC13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(294, 294, 294))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(lb_imgPC29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lb_imgPC30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lb_imgPC31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lb_imgPC32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(294, 294, 294)))
                .addGap(51, 51, 51))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_imgPC1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_imgPC9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_imgPC17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_imgPC25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_imgPC32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 70, 1140, 700));

        jPanel2.setBackground(new java.awt.Color(1, 26, 93));

        pn_LAS.setBackground(new java.awt.Color(244, 244, 244));
        pn_LAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LASMouseClicked(evt);
            }
        });

        lb_LAS.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_LAS.setText("LAS");

        javax.swing.GroupLayout pn_LASLayout = new javax.swing.GroupLayout(pn_LAS);
        pn_LAS.setLayout(pn_LASLayout);
        pn_LASLayout.setHorizontalGroup(
            pn_LASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LASLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lb_LAS)
                .addGap(41, 41, 41))
        );
        pn_LASLayout.setVerticalGroup(
            pn_LASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_LAS)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pn_LDM.setBackground(new java.awt.Color(81, 209, 12));
        pn_LDM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LDMMouseClicked(evt);
            }
        });

        lb_LDM.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_LDM.setText("LDM");

        javax.swing.GroupLayout pn_LDMLayout = new javax.swing.GroupLayout(pn_LDM);
        pn_LDM.setLayout(pn_LDMLayout);
        pn_LDMLayout.setHorizontalGroup(
            pn_LDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LDMLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lb_LDM)
                .addGap(41, 41, 41))
        );
        pn_LDMLayout.setVerticalGroup(
            pn_LDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LDMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_LDM)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pn_LDS.setBackground(new java.awt.Color(81, 209, 12));
        pn_LDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LDSMouseClicked(evt);
            }
        });

        lb_LDS.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_LDS.setText("LDS");

        javax.swing.GroupLayout pn_LDSLayout = new javax.swing.GroupLayout(pn_LDS);
        pn_LDS.setLayout(pn_LDSLayout);
        pn_LDSLayout.setHorizontalGroup(
            pn_LDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LDSLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lb_LDS)
                .addGap(41, 41, 41))
        );
        pn_LDSLayout.setVerticalGroup(
            pn_LDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LDSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_LDS)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pn_LPG.setBackground(new java.awt.Color(81, 209, 12));
        pn_LPG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LPGMouseClicked(evt);
            }
        });

        lb_LPG.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_LPG.setText("LPG");

        javax.swing.GroupLayout pn_LPGLayout = new javax.swing.GroupLayout(pn_LPG);
        pn_LPG.setLayout(pn_LPGLayout);
        pn_LPGLayout.setHorizontalGroup(
            pn_LPGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LPGLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lb_LPG)
                .addGap(41, 41, 41))
        );
        pn_LPGLayout.setVerticalGroup(
            pn_LPGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LPGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_LPG)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pn_LSO.setBackground(new java.awt.Color(81, 209, 12));
        pn_LSO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LSOMouseClicked(evt);
            }
        });

        lb_LSO.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_LSO.setText("LSO");

        javax.swing.GroupLayout pn_LSOLayout = new javax.swing.GroupLayout(pn_LSO);
        pn_LSO.setLayout(pn_LSOLayout);
        pn_LSOLayout.setHorizontalGroup(
            pn_LSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LSOLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lb_LSO)
                .addGap(41, 41, 41))
        );
        pn_LSOLayout.setVerticalGroup(
            pn_LSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LSOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_LSO)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        lb_nombresalon.setText("LAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_LAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_LDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_LDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_LPG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_LSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nombresalon)
                    .addComponent(lb_pc))
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_nombresalon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_pc))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pn_LAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_LDM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_LDS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_LPG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_LSO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 0, 1140, -1));

        jPanel1.setBackground(new java.awt.Color(107, 8, 48));

        lb_usuario.setBackground(new java.awt.Color(255, 255, 255));
        lb_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_usuarioMouseClicked(evt);
            }
        });

        lb_nomusuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_nomusuario.setForeground(new java.awt.Color(255, 255, 255));
        lb_nomusuario.setText("jLabel2");

        lb_nomusuario1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_nomusuario1.setForeground(new java.awt.Color(255, 255, 255));
        lb_nomusuario1.setText("usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nomusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_nomusuario1)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_nomusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_nomusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 250, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-amarillo.png"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 80, -1));

        lb_hora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-rojo.png"))); // NOI18N
        jPanel5.add(lb_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, -1));

        lb_fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computadora-verde.png"))); // NOI18N
        jPanel5.add(lb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, -1));

        libre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        libre.setText("Mantenimiento");
        jPanel5.add(libre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 140, 40));

        libre1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        libre1.setText("Ocupada");
        jPanel5.add(libre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 90, 30));

        libre2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        libre2.setText("Libre");
        jPanel5.add(libre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_usuarioMouseClicked
        cerrar();
    }//GEN-LAST:event_lb_usuarioMouseClicked

    private void pn_LASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LASMouseClicked
        lb_nombresalon.setText(lb_LAS.getText());
        cargar(lb_nombresalon.getText());
        salon(lb_nombresalon.getText());
    }//GEN-LAST:event_pn_LASMouseClicked

    private void pn_LDMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LDMMouseClicked
        lb_nombresalon.setText(lb_LDM.getText());
        cargar(lb_nombresalon.getText());
        salon(lb_nombresalon.getText());
    }//GEN-LAST:event_pn_LDMMouseClicked

    private void pn_LDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LDSMouseClicked
        lb_nombresalon.setText(lb_LDS.getText());
        cargar(lb_nombresalon.getText());
        salon(lb_nombresalon.getText());
    }//GEN-LAST:event_pn_LDSMouseClicked

    private void pn_LPGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LPGMouseClicked
         lb_nombresalon.setText(lb_LPG.getText());
         cargar(lb_nombresalon.getText());
         salon(lb_nombresalon.getText());
    }//GEN-LAST:event_pn_LPGMouseClicked

    private void pn_LSOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LSOMouseClicked
        lb_nombresalon.setText(lb_LSO.getText());
        cargar(lb_nombresalon.getText());
        salon(lb_nombresalon.getText());
    }//GEN-LAST:event_pn_LSOMouseClicked

    private void lb_imgPC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC1MouseClicked
        pc_reservar(lb_imgPC1);
    }//GEN-LAST:event_lb_imgPC1MouseClicked

    private void lb_imgPC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC2MouseClicked
        pc_reservar(lb_imgPC2);
    }//GEN-LAST:event_lb_imgPC2MouseClicked

    private void lb_imgPC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC3MouseClicked
        pc_reservar(lb_imgPC3);
    }//GEN-LAST:event_lb_imgPC3MouseClicked

    private void lb_imgPC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC4MouseClicked
        pc_reservar(lb_imgPC4);
    }//GEN-LAST:event_lb_imgPC4MouseClicked

    private void lb_imgPC5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC5MouseClicked
        pc_reservar(lb_imgPC5);
    }//GEN-LAST:event_lb_imgPC5MouseClicked

    private void lb_imgPC6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC6MouseClicked
        pc_reservar(lb_imgPC6);
    }//GEN-LAST:event_lb_imgPC6MouseClicked

    private void lb_imgPC7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC7MouseClicked
        pc_reservar(lb_imgPC7);
    }//GEN-LAST:event_lb_imgPC7MouseClicked

    private void lb_imgPC8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC8MouseClicked
        pc_reservar(lb_imgPC8);
    }//GEN-LAST:event_lb_imgPC8MouseClicked

    private void lb_imgPC9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC9MouseClicked
        pc_reservar(lb_imgPC9);
    }//GEN-LAST:event_lb_imgPC9MouseClicked

    private void lb_imgPC10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC10MouseClicked
        pc_reservar(lb_imgPC10);
    }//GEN-LAST:event_lb_imgPC10MouseClicked

    private void lb_imgPC11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC11MouseClicked
        pc_reservar(lb_imgPC11);
    }//GEN-LAST:event_lb_imgPC11MouseClicked

    private void lb_imgPC12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC12MouseClicked
        pc_reservar(lb_imgPC12);
    }//GEN-LAST:event_lb_imgPC12MouseClicked

    private void lb_imgPC13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC13MouseClicked
        pc_reservar(lb_imgPC13);
    }//GEN-LAST:event_lb_imgPC13MouseClicked

    private void lb_imgPC14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC14MouseClicked
        pc_reservar(lb_imgPC14);
    }//GEN-LAST:event_lb_imgPC14MouseClicked

    private void lb_imgPC15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC15MouseClicked
        pc_reservar(lb_imgPC15);
    }//GEN-LAST:event_lb_imgPC15MouseClicked

    private void lb_imgPC16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC16MouseClicked
        pc_reservar(lb_imgPC16);
    }//GEN-LAST:event_lb_imgPC16MouseClicked

    private void lb_imgPC17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC17MouseClicked
        pc_reservar(lb_imgPC17);
    }//GEN-LAST:event_lb_imgPC17MouseClicked

    private void lb_imgPC18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC18MouseClicked
        pc_reservar(lb_imgPC18);
    }//GEN-LAST:event_lb_imgPC18MouseClicked

    private void lb_imgPC19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC19MouseClicked
        pc_reservar(lb_imgPC19);
    }//GEN-LAST:event_lb_imgPC19MouseClicked

    private void lb_imgPC20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC20MouseClicked
        pc_reservar(lb_imgPC20);
    }//GEN-LAST:event_lb_imgPC20MouseClicked

    private void lb_imgPC21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC21MouseClicked
        pc_reservar(lb_imgPC21);
    }//GEN-LAST:event_lb_imgPC21MouseClicked

    private void lb_imgPC22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC22MouseClicked
        pc_reservar(lb_imgPC22);
    }//GEN-LAST:event_lb_imgPC22MouseClicked

    private void lb_imgPC23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC23MouseClicked
        pc_reservar(lb_imgPC23);
    }//GEN-LAST:event_lb_imgPC23MouseClicked

    private void lb_imgPC24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC24MouseClicked
        pc_reservar(lb_imgPC24);
    }//GEN-LAST:event_lb_imgPC24MouseClicked

    private void lb_imgPC25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC25MouseClicked
        pc_reservar(lb_imgPC25);
    }//GEN-LAST:event_lb_imgPC25MouseClicked

    private void lb_imgPC26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC26MouseClicked
        pc_reservar(lb_imgPC26);
    }//GEN-LAST:event_lb_imgPC26MouseClicked

    private void lb_imgPC27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC27MouseClicked
        pc_reservar(lb_imgPC27);
    }//GEN-LAST:event_lb_imgPC27MouseClicked

    private void lb_imgPC28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC28MouseClicked
        pc_reservar(lb_imgPC28);
    }//GEN-LAST:event_lb_imgPC28MouseClicked

    private void lb_imgPC29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC29MouseClicked
        pc_reservar(lb_imgPC29);
    }//GEN-LAST:event_lb_imgPC29MouseClicked

    private void lb_imgPC30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC30MouseClicked
        pc_reservar(lb_imgPC30);
    }//GEN-LAST:event_lb_imgPC30MouseClicked

    private void lb_imgPC31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC31MouseClicked
        pc_reservar(lb_imgPC31);
    }//GEN-LAST:event_lb_imgPC31MouseClicked

    private void lb_imgPC32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgPC32MouseClicked
        pc_reservar(lb_imgPC32);
    }//GEN-LAST:event_lb_imgPC32MouseClicked

    private void bt_registrarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarClaseActionPerformed
        switch(lb_nombresalon.getText()) {
            case "LAS":
                pn_LAS.setBackground(new Color(255,0,0));
                reservar( "LAS");
            break;
            case "LDM":
                pn_LDM.setBackground(new Color(255,0,0));
                reservar( "LDM");
            break;
            case "LDS":
                pn_LDS.setBackground(new Color(255,0,0));
                reservar( "LDS");
            break;
            case "LPG":
                pn_LPG.setBackground(new Color(255,0,02));
                reservar( "LPG");
            break;
            case "LSO":
                pn_LSO.setBackground(new Color(255,0,0));
                reservar( "LSO");
            break;
            }  
    }//GEN-LAST:event_bt_registrarClaseActionPerformed
    public void cerrar(){
        String equipo_usado=lb_pc.getText(),nom=lb_nomusuario.getText();
        Object [] opciones ={"Aceptar","Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"Desea cerrar sesión","Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION)
        {
        Observaciones ventana = new Observaciones( FECHA, HORA, equipo_usado, nom,salonr,TIPO);
        ventana.setVisible(true);
        this.setVisible(false);
        }else{
        }
    }
    private void verificar(String tipo) {
        try {
            String asunto="",mensaje="";
            Connection connection = Base_datos.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            ps = connection.prepareStatement("SELECT Asunto,Cuerpo FROM Mensajes where TipoDeUsuarioAlQueSeDirige='"+tipo+"' AND Estado='Activo'"); 
            rs = ps.executeQuery();
            while(rs.next()){
                asunto=rs.getString("Asunto");
                mensaje=rs.getString("Cuerpo");
                    if(!"".equals(asunto)){
                    mensaje ventana = new mensaje(mensaje,asunto);
                    ventana.setAlwaysOnTop(true);
                    ventana.setVisible(true);
                    this.setVisible(false);
                    }
            }
            ps = connection.prepareStatement("SELECT Asunto,Cuerpo FROM Mensajes where TipoDeUsuarioAlQueSeDirige='Todos' AND Estado='Activo'"); 
            rs = ps.executeQuery();
            while(rs.next()){
                asunto=rs.getString("Asunto");
                mensaje=rs.getString("Cuerpo");
                    if(!"".equals(asunto)){
                    mensaje ventana = new mensaje(mensaje,asunto);
                    ventana.setAlwaysOnTop(true);
                    ventana.setVisible(true);
                    this.setVisible(false);
                    }
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.toString());
        }       
    }
    private void cargar(String salon) {
        try {
            String tipo=salon,estado="",id="";
            int i=0;
            JLabel a[] = {lb_imgPC1,lb_imgPC10,lb_imgPC11,lb_imgPC12,lb_imgPC13,lb_imgPC14,lb_imgPC15,lb_imgPC16,lb_imgPC17,lb_imgPC18,lb_imgPC19,lb_imgPC2,lb_imgPC20,lb_imgPC21,lb_imgPC22,lb_imgPC23,lb_imgPC24,lb_imgPC25,lb_imgPC26,lb_imgPC27,lb_imgPC28,lb_imgPC29,lb_imgPC3,lb_imgPC30,lb_imgPC31,lb_imgPC32,lb_imgPC4,lb_imgPC5,lb_imgPC6,lb_imgPC7,lb_imgPC8,lb_imgPC9};
            Connection connection = Base_datos.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            ps = connection.prepareStatement("SELECT  Id,Estado  FROM Equipos where Salon='"+tipo+"'ORDER BY Id ASC"); 
            rs = ps.executeQuery();
            while(rs.next()){
                id=rs.getString("Id");
                estado=rs.getString("Estado");
                a[i].setText(id);
                cargar2(a[i],estado);
                i=1+i;
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.toString());
        }       
    }
    private void cargar2  (JLabel pc,String estado) {
        try {
           switch(estado) {
            case "Activo":
                rsscalelabel.RSScaleLabel.setScaleLabel(pc,"src/img/computadora-verde.png");
            break;
            case "Ocupada":
                rsscalelabel.RSScaleLabel.setScaleLabel(pc,"src/img/computadora-rojo.png");
            break;
            case "Mantenimiento":
                rsscalelabel.RSScaleLabel.setScaleLabel(pc,"src/img/computadora-amarillo.png");
            break;
            
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.toString());
        }       
    }
    private void reservar (String salon){
        try{
            Connection con=Base_datos.getConnection();
            PreparedStatement ps=con.prepareStatement("UPDATE Equipos SET Estado='Ocupada' WHERE Salon='"+salon+"'");
            ps.executeUpdate();
            PreparedStatement ps2=con.prepareStatement("UPDATE Salones SET Estado='OCUPADO' WHERE id='"+salon+"'");
            ps2.executeUpdate();
            salonr=salon;
            JOptionPane.showMessageDialog(null,"salon Reservado","salon modificado",JOptionPane.PLAIN_MESSAGE,new ImageIcon("src/img/accept.png")); 
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    private void salon  (String salon) {
        try {
            
           switch(salon) {
            case "LAS":
                pn_LAS.setBackground(new Color(244,244,244));
                CAMBIAR  (pn_LDM,"LDM");
                CAMBIAR  (pn_LDS,"LDS");
                CAMBIAR  (pn_LPG,"LPG");
                CAMBIAR  (pn_LSO,"LSO");
                jLabel1.setText("Laboratorio de Administración de servidores");
            break;
            case "LDM":
                pn_LDM.setBackground(new Color(244,244,244));
                CAMBIAR  (pn_LAS,"LAS");
                CAMBIAR  (pn_LDS,"LDS");
                CAMBIAR  (pn_LPG,"LPG");
                CAMBIAR  (pn_LSO,"LSO");
                jLabel1.setText("Laboratorio de Dispocitivos Moviles");
            break;
            case "LDS":
                pn_LDS.setBackground(new Color(244,244,244));
                CAMBIAR  (pn_LAS,"LAS");
                CAMBIAR  (pn_LDM,"LDM");
                CAMBIAR  (pn_LPG,"LPG");
                CAMBIAR  (pn_LSO,"LSO");
                jLabel1.setText("Laboratorio de Desarrollo de Software");
            break;
            case "LPG":
                pn_LPG.setBackground(new Color(244,244,244));
                CAMBIAR  (pn_LAS,"LAS");
                CAMBIAR  (pn_LDS,"LDS");
                CAMBIAR  (pn_LDM,"LDM");
                CAMBIAR  (pn_LSO,"LSO");
                jLabel1.setText("Laborio de  Programacion General");
            break;
            case "LSO":
                pn_LSO.setBackground(new Color(244,244,244));
                CAMBIAR  (pn_LAS,"LAS");
                CAMBIAR  (pn_LDS,"LDS");
                CAMBIAR  (pn_LPG,"LPG");
                CAMBIAR  (pn_LDM,"LDM");
                jLabel1.setText("Laboratorio de Sistemas Operativos");
            break;
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.toString());
        }       
    }
    private void CAMBIAR  (JPanel salon,String salon_id) {
        String  estado="";
        try {
            Connection con=Base_datos.getConnection();
            ResultSet rs;
            PreparedStatement ps=con.prepareStatement("SELECT Estado FROM Salones WHERE  Id='"+salon_id+"'");
            
            rs=ps.executeQuery();
            while(rs.next()){
            estado=rs.getString("Estado");
            }
           switch(estado) {
               //verde
            case "Activo":
                salon.setBackground(new Color(81,209,12));
            break;
            //gris selecionado
            case "OCUPADO":
                salon.setBackground(new Color(255,0,0));
            break;
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.toString());
        }       
    }
    
    public void ATUALIZACION_REAL() {
        Timer timer = new Timer();
    TimerTask task = new TimerTask() {
        public void run() {
            cargar(lb_nombresalon.getText());
        }
    };
    timer.schedule(task, 0,500);
    }
    private void pc_reservar  (JLabel pc) {
      
        String estadoi="";
        try{
        Connection connection = Base_datos.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            ps = connection.prepareStatement("SELECT  Estado  FROM Equipos where Id='"+pc.getText()+"'"); 
            rs = ps.executeQuery();
            while(rs.next()){
                estadoi=rs.getString("Estado");
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        if(estadoi.equals("Activo")){
            if(lb_pc.getText().isEmpty()){
                Object [] opciones ={"Aceptar","Cancelar"};
                int eleccion = JOptionPane.showOptionDialog(rootPane,"Desea reservar la pc: "+pc.getText(),"Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
                String estado="Ocupada",id=pc.getText();
                if (eleccion == JOptionPane.YES_OPTION)
                {   
                    try{
                        Connection con=Base_datos.getConnection();
                        PreparedStatement ps=con.prepareStatement("UPDATE Equipos SET Estado=? WHERE Id=?");
                        ps.setString(1, estado);
                        ps.setString(2, id);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Computadora Reservada","Computadora modificado",JOptionPane.PLAIN_MESSAGE,new ImageIcon("src/img/accept.png")); 
                    }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, ex.toString());
                    }
                    lb_pc.setText(pc.getText());
                    bt_registrarClase.setVisible(false);
                } 
            }else{
                JOptionPane.showMessageDialog(null,"Ya Reservada la Computadora"+lb_pc.getText(),"Computadora modificado",JOptionPane.PLAIN_MESSAGE,new ImageIcon("src/img/cerrarinicio.png"));
            }
        }
        if(estadoi.equals("Ocupada")){
           JOptionPane.showMessageDialog(null,"LA Computadora "+pc.getText()+" esta  Ocupada","Computadora Ocupada ",JOptionPane.PLAIN_MESSAGE,new ImageIcon("src/img/cerrarinicio.png"));  
        }
        if(estadoi.equals("Mantenimiento")){
          JOptionPane.showMessageDialog(null,"LA Computadora "+pc.getText()+" esta  en Mantenimiento","Computadora en Mantenimiento",JOptionPane.PLAIN_MESSAGE,new ImageIcon("src/img/cerrarinicio.png"));   
        }
    }
    private String salon_tiempo_real  (JLabel salon) {
        String Estado="";
        try{
            Connection connection = Base_datos.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            ps = connection.prepareStatement("SELECT Estado FROM Salones where Id='"+salon.getText()+"'"); 
            rs = ps.executeQuery();
            while(rs.next()){
                Estado=rs.getString("Estado");
            }
            return Estado;
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        return Estado;
    }
        
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_registrarClase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lb_LAS;
    private javax.swing.JLabel lb_LDM;
    private javax.swing.JLabel lb_LDS;
    private javax.swing.JLabel lb_LPG;
    private javax.swing.JLabel lb_LSO;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_hora;
    private javax.swing.JLabel lb_imgPC1;
    private javax.swing.JLabel lb_imgPC10;
    private javax.swing.JLabel lb_imgPC11;
    private javax.swing.JLabel lb_imgPC12;
    private javax.swing.JLabel lb_imgPC13;
    private javax.swing.JLabel lb_imgPC14;
    private javax.swing.JLabel lb_imgPC15;
    private javax.swing.JLabel lb_imgPC16;
    private javax.swing.JLabel lb_imgPC17;
    private javax.swing.JLabel lb_imgPC18;
    private javax.swing.JLabel lb_imgPC19;
    private javax.swing.JLabel lb_imgPC2;
    private javax.swing.JLabel lb_imgPC20;
    private javax.swing.JLabel lb_imgPC21;
    private javax.swing.JLabel lb_imgPC22;
    private javax.swing.JLabel lb_imgPC23;
    private javax.swing.JLabel lb_imgPC24;
    private javax.swing.JLabel lb_imgPC25;
    private javax.swing.JLabel lb_imgPC26;
    private javax.swing.JLabel lb_imgPC27;
    private javax.swing.JLabel lb_imgPC28;
    private javax.swing.JLabel lb_imgPC29;
    private javax.swing.JLabel lb_imgPC3;
    private javax.swing.JLabel lb_imgPC30;
    private javax.swing.JLabel lb_imgPC31;
    private javax.swing.JLabel lb_imgPC32;
    private javax.swing.JLabel lb_imgPC4;
    private javax.swing.JLabel lb_imgPC5;
    private javax.swing.JLabel lb_imgPC6;
    private javax.swing.JLabel lb_imgPC7;
    private javax.swing.JLabel lb_imgPC8;
    private javax.swing.JLabel lb_imgPC9;
    private javax.swing.JLabel lb_nombresalon;
    private javax.swing.JLabel lb_nomusuario;
    private javax.swing.JLabel lb_nomusuario1;
    private javax.swing.JLabel lb_pc;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JLabel libre;
    private javax.swing.JLabel libre1;
    private javax.swing.JLabel libre2;
    private javax.swing.JPanel pn_LAS;
    private javax.swing.JPanel pn_LDM;
    private javax.swing.JPanel pn_LDS;
    private javax.swing.JPanel pn_LPG;
    private javax.swing.JPanel pn_LSO;
    // End of variables declaration//GEN-END:variables
}
